<a href="https://colab.research.google.com/github/k-sahaj/DS-projects/blob/main/Credit%20card%20fraud%20detection/Credit_Card_Fraud_Detection_using_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CREDIT CARD FRAUD DETECTION USING ML

Dataset used- creditcard.csv (from kaggle)

Importing the dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [16]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('/content/creditcard.csv')
df = credit_card_data

Understanding the data

In [17]:
df.sample(5)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
41410,40669.0,1.202794,-1.051894,0.397401,-0.729877,-1.181533,-0.312882,-0.785101,-0.025711,-0.342830,...,0.132383,-0.014900,-0.158104,-0.455944,0.306581,-0.256594,0.000616,0.038325,133.50,0
164721,116944.0,-0.113061,1.124539,-1.723217,-0.930440,1.941930,-0.334958,1.627842,-0.446456,-0.130459,...,0.050590,0.375679,-0.382428,-0.345234,-0.107264,0.547191,-0.289446,-0.078712,31.44,0
63684,50829.0,0.872958,-0.983174,1.085962,-0.549173,-0.759133,1.583813,-0.961531,0.642859,2.533659,...,-0.089666,0.369057,0.054240,-0.583125,0.295059,-0.646320,0.184745,0.031811,63.33,0
125534,77706.0,0.977130,-0.462029,-0.380415,-0.032348,-0.159993,-0.391100,0.266724,0.028393,-0.090391,...,-0.263082,-1.207597,0.027680,-0.320072,0.032466,0.728294,-0.134317,0.002882,146.00,0
140499,83753.0,-0.847440,1.304083,0.870562,0.112307,-0.353656,-1.088710,0.250275,0.381714,-0.323766,...,-0.221239,-0.785214,0.114058,0.301470,-0.171605,0.067525,-0.015029,0.024780,1.98,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231766 entries, 0 to 231765
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    231766 non-null  float64
 1   V1      231766 non-null  float64
 2   V2      231766 non-null  float64
 3   V3      231766 non-null  float64
 4   V4      231766 non-null  float64
 5   V5      231766 non-null  float64
 6   V6      231766 non-null  float64
 7   V7      231766 non-null  float64
 8   V8      231766 non-null  float64
 9   V9      231766 non-null  float64
 10  V10     231766 non-null  float64
 11  V11     231766 non-null  float64
 12  V12     231766 non-null  float64
 13  V13     231766 non-null  float64
 14  V14     231766 non-null  float64
 15  V15     231766 non-null  float64
 16  V16     231766 non-null  float64
 17  V17     231766 non-null  float64
 18  V18     231766 non-null  float64
 19  V19     231766 non-null  float64
 20  V20     231766 non-null  float64
 21  V21     231766 non-null  float64
 22  V22     231766 non-null  float64
 23  V23     231766 non-null  float64
 24  V24     231766 non-null  float64
 25  V25     231766 non-null  float64
 26  V26     231766 non-null  float64
 27  V27     231765 non-null  float64
 28  V28     231765 non-null  float64
 29  Amount  231765 non-null  float64
 30  Class   231765 non-null  float64
dtypes: float64(31)
memory usage: 54.8 MB

In [8]:
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,231766.000000,231766.000000,231766.000000,231766.000000,231766.000000,231766.000000,231766.000000,231766.000000,231766.000000,231766.000000,...,231766.000000,231766.000000,231766.000000,231766.000000,231766.000000,231766.000000,231765.000000,231765.000000,231765.000000,231765.000000
mean,80176.839549,-0.063333,-0.016128,0.165631,0.041052,-0.058072,0.027982,-0.024126,0.003208,0.002663,...,-0.005578,-0.020478,-0.009385,0.000614,0.034814,0.002847,0.000080,0.001723,91.053584,0.001816
std,40112.973801,1.954838,1.671862,1.497778,1.413103,1.377347,1.324713,1.231051,1.208049,1.121443,...,0.743671,0.710479,0.641105,0.606348,0.510071,0.486676,0.402982,0.334538,252.667224,0.042582
min,0.000000,-56.407510,-72.715728,-33.680984,-5.683171,-42.147898,-26.160506,-43.557242,-73.216718,-13.434066,...,-34.830382,-10.933144,-44.807735,-2.836627,-10.295397,-2.604551,-22.565679,-11.710896,0.000000,0.000000
25%,48152.000000,-0.947040,-0.602961,-0.599239,-0.827448,-0.744480,-0.735351,-0.567662,-0.196739,-0.659969,...,-0.225495,-0.533346,-0.166754,-0.349465,-0.276158,-0.330995,-0.069824,-0.048461,6.000000,0.000000
50%,74055.500000,-0.028110,0.066367,0.355713,0.036077,-0.116757,-0.240485,0.012425,0.032520,-0.065536,...,-0.033957,-0.009792,-0.022116,0.047070,0.071165,-0.059743,0.003228,0.015557,23.450000,0.000000
75%,121653.750000,1.245739,0.780962,1.143758,0.829280,0.539713,0.431011,0.536167,0.331832,0.612065,...,0.170156,0.476408,0.128357,0.428151,0.371834,0.252252,0.089202,0.078086,79.990000,0.000000
max,146915.000000,2.454930,22.057729,9.382558,16.875344,34.801666,22.529298,36.877368,20.007208,15.594995,...,27.202839,10.503090,22.528412,4.022866,7.519589,3.517346,12.152401,33.847808,19656.530000,1.000000

In [22]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [24]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

Here,

0 --> Normal Transactions

1 --> Fraudulent transactions

Also, this dataset is highly unbalanced. We have to fix this too.

In [25]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [26]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [27]:
# statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [28]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [29]:
# compare the values for both transactions
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

In [30]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [31]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [32]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
207840,136853.0,-0.301526,1.093745,-0.076447,-0.538132,0.054695,-1.180678,0.658863,0.228963,-0.184923,...,-0.217073,-0.597044,0.141120,0.032389,-0.470699,0.140728,0.118656,0.035184,9.03,0
185767,126815.0,0.062363,1.026578,0.390377,2.831283,1.275211,1.073185,0.794602,0.285890,-1.253578,...,0.143147,0.519333,-0.229324,0.271301,0.123170,0.093095,-0.004476,-0.012830,18.92,0
13824,24510.0,1.111137,0.058045,0.017382,1.249269,0.478713,0.871117,-0.107408,0.130760,1.436603,...,-0.250881,-0.396494,-0.247106,-1.195331,0.737363,-0.300690,-0.003573,-0.004416,58.00,0
227170,144961.0,-1.018265,1.161500,-0.939286,1.068403,1.055049,-1.195065,1.033262,-0.485469,0.314304,...,0.043446,0.732616,-0.114593,0.015654,-0.348252,-0.503062,0.119861,0.496702,12.40,0
34200,37559.0,-0.420801,0.007958,1.031619,-2.200153,0.481123,0.411441,0.697526,0.132609,1.327346,...,-0.186708,-0.322619,-0.172472,-1.223761,-0.105758,-0.995981,-0.002896,-0.101108,44.95,0

In [33]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [34]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [35]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,92206.861789,-0.017958,0.085311,0.010535,-0.040705,-0.062084,-0.032809,-0.050227,0.061372,0.015873,...,0.035856,-0.030290,0.023329,-0.018883,0.03827,0.020957,-0.003585,0.020894,0.000603,79.914756
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.10513,0.041449,0.051648,0.170575,0.075667,122.211321

Splitting the data into Features & Targets

In [37]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']
#print(X)
#print(Y)

In [38]:
#Split the data into Training data & Testing Data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [39]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

In [40]:
print(Y.shape, Y_train.shape, Y_test.shape)

(984,) (787,) (197,)

MODEL TRAINING:

Logistic Regression

In [45]:
model = LogisticRegression()
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [46]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

LogisticRegression()

Model Evaluation:

In [47]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [48]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9555273189326556

In [49]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [50]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9441624365482234